name: FareHunter

on:
  schedule:
    # Corre 4 veces al día (UTC). Ajusta si quieres.
    - cron: "7 3,9,15,21 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Opcional) Diagnóstico rápido: verifica que los secrets están presentes
      - name: Check env presence
        run: |
          python - <<'PY'
          import os
          print("HAS_KEY   =", bool(os.getenv("AMADEUS_KEY")))
          print("HAS_SECRET=", bool(os.getenv("AMADEUS_SECRET")))
          print("HAS_TG_TK =", bool(os.getenv("TELEGRAM_TOKEN")))
          print("HAS_TG_CH =", bool(os.getenv("TELEGRAM_CHAT")))
          PY
        env:
          AMADEUS_KEY: ${{ secrets.AMADEUS_KEY }}
          AMADEUS_SECRET: ${{ secrets.AMADEUS_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}

      # Test de Telegram antes de lanzar el scraper (puedes borrar este paso si ya confías)
      - name: Test Telegram connectivity
        run: |
          python - <<'PY'
          import os, requests
          t = os.environ['TELEGRAM_TOKEN']
          c = os.environ['TELEGRAM_CHAT']
          r = requests.post(
              f"https://api.telegram.org/bot{t}/sendMessage",
              data={'chat_id': c, 'text': '🛠️ Workflow iniciado: test OK'},
              timeout=15
          )
          r.raise_for_status()
          print("Telegram test OK")
          PY
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}

      - name: Run FareHunter
        run: python -m app.main
        env:
          AMADEUS_KEY: ${{ secrets.AMADEUS_KEY }}
          AMADEUS_SECRET: ${{ secrets.AMADEUS_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
